### ISSUE TITLE
Add Fact

### ISSUE THREAD

**Issue by gerardtoconnor** [giraffe-fsharp/Giraffe.TokenRouter#2]
https://github.com/giraffe-fsharp/Giraffe.TokenRouter/blob/9bbdaabe71ac385409620eebf3cc9b0fd79d0fb9/tests/Giraffe.TokenRouter.Tests/TokenRouterTests.fs#L1499

**Comment by dustinmoris** [comment]
Good catch! I added the attribute and fixed some runtime error with the test. It needed the `HostString` to be mocked in a slightly different way (due to being a nullable type).
