### ISSUE TITLE
Giraffe.TokenRouter

### ISSUE THREAD

**Issue by forki** [giraffe-fsharp/Giraffe.TokenRouter#6]
Giraffe.TokenRouter 1.0 crashes on runtime when used in combination with Giraffe 5 since it can't load Giraffe 2.0 lib.

Could you please release a version which depends on Giraffe 5?

**Comment by dustinmoris** [comment]
https://www.nuget.org/packages/Giraffe.TokenRouter/2.0.0

Please try this ^

**Comment by forki** [comment]
it works! Thanks for super fast fix
